enum ActionTypes {
    SAVE_CUSTOMERS = "SAVE_CUSTOMERS",
    SAVE_CUSTOMER_APPLICATIONS = "SAVE_CUSTOMER_APPLICATIONS",
    SAVE_CUSTOMER_DETAILS = "SAVE_CUSTOMER_DETAILS",
    LOADING_CUSTOMERS = "LOADING_CUSTOMERS",
    LOADING_CUSTOMER_APPLICATIONS = "LOADING_CUSTOMER_APPLICATIONS",
    LOGOUT_ACTION = "LOGOUT_ACTION",
}

export default ActionTypes;
